---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: asteroid-herder
  name: asteroid-herder

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enquiryapp-deployment
  namespace: asteroid-herder
  labels:
    app.kubernetes.io/name: enquiry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enquiry
  template:
    metadata:
      labels:
        app: enquiry
    spec:
      containers:
      - name: enquiry
        image: enquiry-app:1.0.0
        ports:
        - containerPort: 80
          name: enquiry-app-svc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: enquiry
  name: enquiry-app-svc
  namespace: asteroid-herder
spec:
  ports:
  - nodePort: 30004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: enquiry
  type: NodePort
