apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.label }}
  name: enquiry-app-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - nodePort: {{ .Values.nodePort }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.label }}
  type: {{ .Values.service.type }}
